version: 2.1
orbs:
  heroku: circleci/heroku@0.0.8
workflows:
  build_deploy:
    jobs:
      - build
      - deploy_staging:
        requires: build
        filters:
          branches:
            ignore: master
      - deploy_prod:
        requires: build
        filters:
          branches:
            only: master
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install 
      - run: mkdir junit
      - run: npm install mocha-junit-reporter # just for CircleCI
      - run: npm run report-mocha
      - store_test_results:
          path: junit
      - store_artifacts:
          path: junit
  deploy_staging:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
  deploy_prod:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git: 
        app-name: $HEROKU_APP_NAME_PROD
        


